Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyMovies.Models;
using Newtonsoft.Json;
using IEmailSender = MyMovies.Services.IEmailSender;
using MyMovies.DTO;

namespace MyMovies.Controllers
{
    public class GenreItem
    {
        public int Value { get; set; }
        public string Text { get; set; }
    }
    [Authorize]
    public class MoviesController : Controller
    {
        private readonly MoviesContext _context;
        private readonly int PAGE_SIZE = 12;
        private readonly UserManager<ApplicationUser> _userManager;
        private bool haveMore = true;
        private readonly IEmailSender _emailSender;
        public MoviesController(MoviesContext context, UserManager<ApplicationUser> userManager, IEmailSender emailSender)
        {
            _context = context;
            _userManager = userManager;
            _emailSender = emailSender;
        }

        [Route("Movies/List")] // /Movies/List?search=""&genres=5,4,9&page=5
        public async Task<JsonResult> GetFilteredMovies([FromQuery] string search, [FromQuery] int?[] genres, [FromQuery] string[] langs, [FromQuery] int? page = 1)
        {
            string UserId = (await _userManager.GetUserAsync(HttpContext.User)).Id;

            var movies = _context.Movies.Include("Genres.Genre");
            if (!String.IsNullOrEmpty(search))
            {
                movies = movies.Where(s => s.Title.Contains(search)).Include("Genres.Genre");
            }

            if (genres != null && genres.ToArray().Length != 0)
            {
                movies = movies.Where(m => genres.All(g => m.Genres.Exists(movieGenre => movieGenre.GenreId == g)));
            }

            if (langs.ToArray().Length != 0 && langs[0] != "null")
            {
                movies = movies.Where(m => langs.All(l => l == m.OriginalLanguage));
            }

            if (page != null && page >= 1)
            {
                this.haveMore = movies.Skip(PAGE_SIZE * page.Value).ToArray().Length > 0;
                movies = movies.Skip(PAGE_SIZE * (page.Value - 1)).Take(PAGE_SIZE);
            }

            var ms = movies.Select(m => new MovieDTO(m,
                _context.UserWatchList.Any(x => x.UserId == UserId && x.MovieId == m.Id),
                _context.UserFavoriteMovies.Any(x => x.UserId == UserId && x.MovieId == m.Id)));

            return new JsonResult(JsonConvert.SerializeObject(ms.ToArray()));
        }

        [Route("Movies/WatchList")]
        public async Task<JsonResult> GetUserWatchList()
        {
            string UserId = (await _userManager.GetUserAsync(HttpContext.User)).Id;

            List<int> userWatchList = await _context.UserWatchList.Where(x => x.UserId == UserId).Select(x => x.MovieId).ToListAsync();

            return new JsonResult(JsonConvert.SerializeObject(userWatchList.ToArray()));
        }

        [Route("Movies/Favorites")]
        public async Task<JsonResult> GetUserFavorites()
        {
            string UserId = (await _userManager.GetUserAsync(HttpContext.User)).Id;

            List<int> userFavoriteMovies = await _context.UserFavoriteMovies.Where(x => x.UserId == UserId).Select(x => x.MovieId).ToListAsync();

            return new JsonResult(JsonConvert.SerializeObject(userFavoriteMovies.ToArray()));
        }

        [Route("Movies/Genres")]
        public async Task<JsonResult> GetGenres()
        {
            var genres = await (from g in _context.Genres
                                select new GenreItem { Value = g.Id, Text = g.Name }).ToListAsync();

            return new JsonResult(JsonConvert.SerializeObject(genres.ToArray()));
        }

        [Route("Movies/Languages")]
        public JsonResult GetLanguages()
        {
            var langs = _context.Movies.Select(m => m.OriginalLanguage).Distinct().Take(10).ToList();
            return new JsonResult(JsonConvert.SerializeObject(langs));
        }

        [Route("Movies/More")]
        public JsonResult HaveMore()
        {
            return new JsonResult(new { haveMore = this.haveMore });
        }

        // GET: Movies
        public IActionResult Index()
        {
            return View();
            // string UserId = (await _userManager.GetUserAsync(HttpContext.User)).Id;
            // ViewBag.currentPage = page;
            // ViewBag.searchString = searchString;
            // ViewBag.genreFilter = genreFilter;

            // var genres = from g in _context.Genres
            //              select new GenreItem { Value = g.Id, Text = g.Name };

            // var movies = _context.Movies.Include("Genres.Genre");

            // ViewBag.genresNames = await genres.ToListAsync();

            // if (!String.IsNullOrEmpty(searchString))
            // {
            //     movies = movies.Where(s => s.Title.Contains(searchString)).Include("Genres.Genre");
            // }

            // if (genreFilter != null && genreFilter.ToArray().Length != 0)
            // {
            //     movies = movies.Where(m => m.Genres.Exists(g => genreFilter.Contains(g.GenreId)));
            // }

            // if (page != null && page >= 1)
            // {
            //     movies = movies.Skip(PAGE_SIZE * (page.Value - 1)).Take(PAGE_SIZE);
            // }

            // List<int> userWatchList = await _context.UserWatchList.Where(x => x.UserId == UserId).Select(x => x.MovieId).ToListAsync();
            // List<int> userFavoriteMovies = await _context.UserFavoriteMovies.Where(x => x.UserId == UserId).Select(x => x.MovieId).ToListAsync();

            // ViewBag.userWatchList = userWatchList;
            // ViewBag.userFavoriteMovies = userFavoriteMovies;

            // return View(await movies.ToListAsync());
        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            string UserId = (await _userManager.GetUserAsync(HttpContext.User)).Id;

            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .Include("Genres.Genre").FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            ViewBag.isInWatchList = await _context.UserWatchList.AnyAsync(x => x.UserId == UserId && x.MovieId == id);
            ViewBag.isFavoriteMovie = await _context.UserFavoriteMovies.AnyAsync(x => x.UserId == UserId && x.MovieId == id);

            return View(movie);
        }

        [Route("Movies/Details/{id}/Trailer")]
        public async Task<JsonResult> TrailerId(int id)
        {
            var movieId = this.RouteData.Values["id"];
            object value = null;

            using (HttpClient client = new HttpClient())
            {
                HttpResponseMessage response = null;

                try
                {
                    response = await client.GetAsync("https://api.themoviedb.org/3/movie/" + movieId + "/videos?api_key=9389b2a38d75d7cb06f3193665ee0e56&language=en-US");
                    response.EnsureSuccessStatusCode();
                    string body = await response.Content.ReadAsStringAsync();

                    value = new { data = JsonConvert.DeserializeObject(body) };
                }
                catch (Exception e)
                {
                    value = new { ok = false, message = e.Message };
                }
            }

            return new JsonResult(value);
        }

        // GET: Movies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,ReleaseYear,Rating,MovieLength,CreatedDate,CreatedBy")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                _context.Add(movie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,ReleaseYear,Rating,MovieLength,CreatedDate,CreatedBy")] Movie movie)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

Controllers/UserFavoriteMoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyMovies.Models;

namespace MyMovies.Controllers
{
    [Authorize]
    public class UserFavoriteMoviesController : Controller
    {
        private readonly MoviesContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public UserFavoriteMoviesController(MoviesContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: UserFavoriteMovies
        public async Task<IActionResult> Index()
        {
            string CurrentUserId = (await _userManager.GetUserAsync(HttpContext.User)).Id;
            var moviesContext = _context.UserFavoriteMovies.Include("Movie.Genres.Genre").Where(u => u.UserId == CurrentUserId);;
            return View(await moviesContext.ToListAsync());
        }

        #region API

        [HttpPost("/api/favorite/{movieId}")]
        public async Task<JsonResult> AddToFavorite(int movieId)
        {
            string UserId = (await _userManager.GetUserAsync(HttpContext.User)).Id;

            UserFavoriteMovies existingMovie = await _context.UserFavoriteMovies.FirstOrDefaultAsync(x => x.UserId == UserId && x.MovieId == movieId);
            if (existingMovie == null)
            {
                UserFavoriteMovies newMovie = new UserFavoriteMovies() { MovieId = movieId, UserId = UserId };
                _context.Add(newMovie);
                await _context.SaveChangesAsync();

                return Json(newMovie);
            }
            else
            {
                Response.StatusCode = (int)HttpStatusCode.Conflict;
                return Json(new { message = $"The movie {movieId} already exist in user favorite", statusCode = Response.StatusCode });
            }
        }

        [HttpDelete("/api/favorite/{movieId}")]
        public async Task<JsonResult> RemoveFromFavorite(int movieId)
        {
            string UserId = (await _userManager.GetUserAsync(HttpContext.User)).Id;

            UserFavoriteMovies existingMovie = await _context.UserFavoriteMovies.FirstOrDefaultAsync(x => x.UserId == UserId && x.MovieId == movieId);
            if (existingMovie != null)
            {
                _context.Remove(existingMovie);
                await _context.SaveChangesAsync();

                return Json(new { Ok = true });
            }
            else
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                return Json(new { message = $"The movie {movieId} not exist in user favorite", statusCode = Response.StatusCode });
            }
        }

        #endregion

        // GET: UserFavoriteMovies/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userFavoriteMovies = await _context.UserFavoriteMovies
                .Include(u => u.Movie)
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (userFavoriteMovies == null)
            {
                return NotFound();
            }

            return View(userFavoriteMovies);
        }

        // GET: UserFavoriteMovies/Create
        public IActionResult Create()
        {
            ViewData["MovieId"] = new SelectList(_context.Movies, "Id", "Id");
            return View();
        }

        // POST: UserFavoriteMovies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,MovieId")] UserFavoriteMovies userFavoriteMovies)
        {
            if (ModelState.IsValid)
            {
                _context.Add(userFavoriteMovies);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MovieId"] = new SelectList(_context.Movies, "Id", "Id", userFavoriteMovies.MovieId);
            return View(userFavoriteMovies);
        }

        // GET: UserFavoriteMovies/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userFavoriteMovies = await _context.UserFavoriteMovies.FindAsync(id);
            if (userFavoriteMovies == null)
            {
                return NotFound();
            }
            ViewData["MovieId"] = new SelectList(_context.Movies, "Id", "Id", userFavoriteMovies.MovieId);
            return View(userFavoriteMovies);
        }

        // POST: UserFavoriteMovies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("UserId,MovieId")] UserFavoriteMovies userFavoriteMovies)
        {
            if (id != userFavoriteMovies.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userFavoriteMovies);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserFavoriteMoviesExists(userFavoriteMovies.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MovieId"] = new SelectList(_context.Movies, "Id", "Id", userFavoriteMovies.MovieId);
            return View(userFavoriteMovies);
        }

        // GET: UserFavoriteMovies/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userFavoriteMovies = await _context.UserFavoriteMovies
                .Include(u => u.Movie)
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (userFavoriteMovies == null)
            {
                return NotFound();
            }

            return View(userFavoriteMovies);
        }

        // POST: UserFavoriteMovies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var userFavoriteMovies = await _context.UserFavoriteMovies.FindAsync(id);
            _context.UserFavoriteMovies.Remove(userFavoriteMovies);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserFavoriteMoviesExists(string id)
        {
            return _context.UserFavoriteMovies.Any(e => e.UserId == id);
        }
    }
}

Views/UserFavoriteMovies/Create.cshtml
@model MyMovies.Models.UserFavoriteMovies

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>UserFavoriteMovies</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MovieId" class="control-label"></label>
                <select asp-for="MovieId" class ="form-control" asp-items="ViewBag.MovieId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/UserFavoriteMovies/Delete.cshtml
@model MyMovies.Models.UserFavoriteMovies

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserFavoriteMovies</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Movie)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Movie.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="UserId" />
        <input type="hidden" asp-for="MovieId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/UserFavoriteMovies/Details.cshtml
@model MyMovies.Models.UserFavoriteMovies

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>UserFavoriteMovies</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Movie)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Movie.Id)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Views/UserFavoriteMovies/Edit.cshtml
@model MyMovies.Models.UserFavoriteMovies

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>UserFavoriteMovies</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="UserId" />
            <input type="hidden" asp-for="MovieId" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/UserFavoriteMovies/Index.cshtml
@model IEnumerable<MyMovies.Models.UserFavoriteMovies>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>




<div class="row">
    @if (Model.Count() == 0)
    {
        <h3>You Watch List is empty</h3>

    }
    else
    {
        @foreach (var item in Model)
        {
            <div id="favorite-movie-@item.MovieId" class="col-md-3">
                <div class="card">
                    <a asp-controller="Movies" asp-action="Details" asp-route-id="@item.MovieId">
                        <section class="movie_image">
                            <img class="movie_poster" src="@Html.DisplayFor(modelItem => item.Movie.ImagePath)" alt="As Above So Below" />
                        </section>
                    </a>
                    <section class="center">
                        <div class="about_movie">
                            <h3>@Html.DisplayFor(modelItem => item.Movie.Title)</h3>
                            <div class="movie_info">
                                <p>@Html.DisplayFor(modelItem => item.Movie.ReleaseYear)</p>
                                <p>
                                    <!-- @Html.DisplayFor(modelItem => item.Movie.MovieLength) -->

                                </p>
                                @foreach (var Genre in item.Movie.Genres)
                                {
                                    <p>@Html.DisplayFor(modelItem => Genre.Genre.Name) </p>

                                }

                            </div>
                            <div class="movie_desc">
                                <p class="block-with-text">@Html.DisplayFor(modelItem => item.Movie.Description)</p>
                            </div>
                            <div class="button-group">
                                <button type="button" class="remove-favorite-btn btn" data-id="@item.MovieId">
                                    <span class="glyphicon glyphicon-star"></span>
                                    <!-- Remove from favorite -->
                                </button>
                            </div>
                        </div>

                    </section>
                </div>
            </div>
            <!--
                @Html.DisplayFor(modelItem => item.Movie.Id)

                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ })
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ }) -->
        }
    }
    <div class="bg">
        <img src="" alt="background">
    </div>
</div>